/** Semantic Tailwind class strings composed from design tokens */
export const colorClasses = {
  surface: "bg-ink",
  surfaceRaised: "bg-ink-2",
  surfaceOverlay: "bg-ink/70",
  surfaceWhite: "bg-white",
  textPrimary: "text-white",
  textMuted: "text-w-60",
  textSubtle: "text-w-30",
  textDim: "text-w-20",
  textFaint: "text-w-15",
  textGhost: "text-w-08",
  textAccent: "text-accent",
  textAccentBright: "text-accent-bright",
  textInk: "text-ink",
  textError: "text-error",
  textStatusOnline: "text-status-online",
  bgStatusOnline: "bg-status-online",
  borderDefault: "border-bdr",
  borderMid: "border-bdr-mid",
  borderInput: "border-bdr-input",
  borderBright: "border-bdr-bright",
  borderWhite: "border-white",
  borderWhite18: "border-white/18",
  borderWhite15: "border-white/15",
  borderWhite85: "border-white/85",
  decorationSubtle: "decoration-w-30",
  decorationDim: "decoration-w-20",
  decorationWhite: "decoration-white",
  decorationAccent: "decoration-accent",
  bgAccent: "bg-accent",
  bgWhite: "bg-white",
  imageBrightness: "brightness-[0.72] group-hover:brightness-[0.92]",
} as const;

export const layoutClasses = {
  maxWidthPage: "max-w-[1440px]",
  aboutSectionShell: "mx-auto w-full max-w-[1440px] px-page",
  maxWidthAboutProse: "max-w-[620px]",
  maxWidthAboutGrid: "max-w-[720px]",
  maxWidthAboutQuote: "max-w-[760px]",
  maxWidthAboutWide: "max-w-[900px]",
  aboutPhotoMax: "max-w-[240px]",
  caseStudyTextShell: "mx-auto w-full max-w-[1440px]",
  maxWidthContent: "max-w-[1200px]",
  maxWidthProse: "max-w-[720px]",
  caseStudyModule: "mx-auto w-full max-w-[1044px]",
  maxWidthChat: "max-w-[820px]",
  maxWidthLead: "max-w-[640px]",
  maxWidthDeliverable: "max-w-[680px]",
  maxWidthImage: "max-w-[1400px]",
  homeSectionInner: "mx-auto w-full max-w-[1400px] px-page",
  maxWidthChapter: "max-w-[1200px]",
  maxWidthChatMin: "max-w-[min(100%,820px)]",
  maxWidthLegacyProse: "max-w-3xl",
  radius: "rounded-[2px]",
  radiusBubbleUser: "rounded-[12px_2px_12px_12px]",
  radiusBubbleAssistant: "rounded-[2px_12px_12px_12px]",
  aspectVideo: "aspect-video",
  aspectShort: "aspect-[21/7]",
  aspectTall: "aspect-[4/3]",
  caseStudyHeroImage: "relative aspect-video max-h-[50vh] w-full overflow-hidden sm:max-h-[55vh]",
  minHeightAppWide: "min-h-[80vh]",
  appWideImage:
    "max-h-[calc(80vh-8rem)] w-auto max-w-full object-contain sm:max-h-[calc(80vh-12rem)]",
} as const;

export const spacingClasses = {
  pagePadX: "px-page",
  pagePadXWide: "px-page",
  pagePadXMobile: "px-7",
  pagePadXWideOnly: "px-7",
  pagePadXSmOnly: "px-7",
  pagePadXSm6: "px-7 sm:px-7",
  pageTopPad: "pt-page-top",
  heroPadBottom: "pb-12 sm:pb-[72px]",
  caseStudyHeroTextPad: "pb-10 sm:pb-12",
  sectionPadY: "py-24",
  sectionPadYLarge: "py-[120px]",
  sectionPadYXL: "sm:py-32",
  sectionTypoY: "py-[100px]",
  chapterBlockPad: "py-24",
  deliverableBlockPad: "pb-24",
  nextProjectPad: "py-20",
  metaStripPad: "py-8",
  captionPad: "py-3.5",
  footerPad: "px-page py-8",
  workHeaderPad: "px-page pt-page-top pb-16",
  aboutHeroPad: "pt-page-top pb-24",
  aboutCtaPad: "pb-[120px] pt-24",
  workGridPad: "px-page py-12",
  workHeaderGap: "gap-10",
  menuOverlayPad: "px-[80px]",
  menuFooterPos: "bottom-12 left-[80px]",
  menuNavGap: "space-y-6",
  imageAppPad: "px-7 py-16 sm:px-10 sm:py-24",
  imageContainPad: "px-page py-16 sm:py-24",
  imageContainPadLoose: "pt-16 pb-16 sm:pt-20 sm:pb-24",
  imageContainInsetLoose: "px-8 sm:px-20",
  imageContainInsetLooseWide: "px-16 sm:px-32",
  paragraphGap: "[&+&]:mt-[18px]",
  metaCardPy: "py-[18px]",
  metaCardPx: "px-7",
  metaCardPad: "py-[18px] px-7",
  serviceCardPad: "p-7",
  currentlyRowPad: "py-6",
  currentlyRowFirstPt: "pt-0",
  blockquotePad: "pl-8",
  listPad: "pl-6",
  tagPad: "px-3 py-1",
  mdxContentPt: "pt-12",
  pageBottomPad: "pb-24",
  docHeroPt: "pt-24 sm:pt-32",
  dsSectionPad: "py-16 sm:py-20",
  dsTypeSpecPad: "py-8",
  dsNavPb: "pb-8",
  docSurfacePad: "p-6",
  docDemoPad: "px-6 py-8",
  footerHairline: "mt-[3px]",
  footerFlexGap: "gap-4",
  footerLinkGap: "gap-6",
  underlineOffsetSm: "underline-offset-[4px]",
  underlineOffsetMd: "underline-offset-[6px]",
  filterTabOffset: "underline-offset-[6px]",
  hamburgerGap: "gap-[6px]",
  hamburgerWidth: "w-[28px]",
  hamburgerShift: "translate-y-[7px]",
  hamburgerShiftNeg: "-translate-y-[7px]",
  hamburgerPos: "fixed top-7 right-9 p-2",
  brandLogoPos: "fixed top-7 left-9 p-2",
  brandLogoSize: "h-9 w-9",
  labelGapMd: "gap-3.5",
  labelGapSm: "gap-3",
  sectionLabelMb: "mb-6",
  eyebrowMb: "mb-5",
  chapterHeadlineMb: "mb-7",
  chapterBlockMb: "mb-20",
  ctaHeadlineMb: "mb-12",
  ctaLinkGap: "gap-3",
  nextProjectLabelMb: "mb-2.5",
  deliverableLabelCol: "sm:grid-cols-[260px_1fr]",
  caseStudySectionGrid: "sm:grid-cols-[260px_1fr]",
  caseStudyChapterGrid: "sm:grid-cols-2",
  deliverableGap: "sm:gap-16",
  caseStudySectionGap: "sm:gap-16",
  deliverablePadY: "py-12",
  deliverableLabelPt: "pt-1",
  deliverableLabelOptical: "relative top-1",
  deliverableTitleOptical: "-mt-1 leading-display",
  deliverableTitleMt: "mt-3",
  deliverableTitleMb: "mb-3",
  productTourDotsPad: "pt-4 pb-1",
  productTourBrandlinePad: "pb-3.5",
  caseStudySectionLabelPt: "pt-1",
  cardPad: "p-card",
  cardBodyGap: "gap-card-image",
  cardTitleStack: "flex flex-col gap-2",
  cardImageGap: "mb-[16px]",
  metaGap: "gap-[12px]",
  metaStripGap: "gap-3",
  gridGap: "gap-x-5 gap-y-8 sm:gap-x-8 sm:gap-y-12",
  gridGapXSm: "sm:gap-x-[72px]",
  filterTabListGap: "gap-6 pb-1.5 sm:gap-8",
  promptChipListGap: "gap-2",
  bubblePad: "px-4 py-3",
  inputPad: "py-2.5 pl-5 sm:py-3 sm:pl-6",
  inputSubmitInset: "pr-12 sm:pr-14",
  inputSubmitPos: "absolute top-1/2 right-3 sm:right-4",
  inputSubmitSize: "h-8 w-8 sm:h-9 sm:w-9",
  chatMessageGap: "gap-3",
  chatPanelPad: "gap-6 pt-5 pb-2 sm:pt-6",
  chatFormPad: "pt-3 pb-0",
  chatPromptMt: "mt-4",
  chatErrorMt: "mt-2",
  chatPagePad: "pt-24 pb-0 lg:pb-24",
  chatTitleMb: "mb-12 lg:mb-16",
  chatHeaderPy: "py-5",
  chatHeaderBalance: "w-[60px]",
  avatarSize: "h-7 w-7",
  avatarMt: "mt-0.5",
  statusDotSize: "h-1.5 w-1.5",
  statusRowGap: "gap-1.5",
  metaCardLabelMb: "mb-2",
  eyebrowBarSm: "w-4",
  eyebrowBarMd: "w-5",
  portraitPos: "absolute right-7 bottom-[clamp(8px,1.5vh,20px)] w-[clamp(200px,28vw,320px)] sm:right-[72px]",
  introStatementPt: "pt-[clamp(72px,12vh,128px)]",
  introClientMt: "mt-[clamp(56px,12vh,160px)]",
  introGreetingPr: "pr-[min(38vw,300px)]",
  ndaBadgePos: "absolute top-3 left-3 z-[2] h-6 w-6 backdrop-blur-[6px]",
  projectCardLogoOverlay: "pointer-events-none absolute inset-0 z-[1] flex items-center justify-center px-6",
  projectCardLogoImage: "h-auto w-1/2",
  projectCardLogoImageCompact: "h-auto w-[220px] sm:w-[320px]",
  arrowNudge: "group-hover:translate-x-2",
} as const;

export const motionClasses = {
  fast: "duration-200",
  default: "duration-300",
  slow: "duration-500",
  medium: "duration-250",
  menu: "duration-350",
  panel: "duration-[380ms]",
  productTourSlide: "duration-[900ms]",
  ease: "ease-[cubic-bezier(0.22,1,0.36,1)]",
  easePanel: "ease-[cubic-bezier(0.4,0,0.2,1)]",
  easeLetter: "cubic-bezier(0.22, 1, 0.36, 1)",
  portraitFade: "duration-600",
} as const;

export const zIndexClasses = {
  modal: "z-[997]",
  menu: "z-[998]",
  menuButton: "z-[999]",
  cursor: "z-[9999]",
  cursorLabel: "z-[9998]",
  raised: "z-[2]",
  sticky: "z-10",
} as const;

export const linkClasses = {
  textLinkSmall:
    "text-left text-link-small underline decoration-link-small underline-offset-[4px] transition-colors hover:text-white hover:decoration-white active:text-accent active:decoration-accent",
  textLinkCta:
    "text-link underline decoration-link underline-offset-[6px] transition-colors hover:text-white hover:decoration-white active:text-accent active:decoration-accent",
  textLinkFooter:
    "text-link-faint no-underline transition-colors hover:text-w-60 active:text-accent",
  textLinkInline:
    "text-link no-underline transition-colors hover:text-white active:text-accent",
  navLink:
    "block origin-left scale-100 no-underline transition-[color,transform] duration-200 ease-out hover:scale-[1.025] text-link-muted hover:text-white active:scale-100 active:text-accent",
  navMeta:
    "font-sans text-small font-normal text-link no-underline transition-colors active:text-accent",
  filterTabBase:
    "border-0 bg-transparent p-0 transition-colors duration-200 active:text-accent active:decoration-accent",
  filterTabActive: "text-white",
  filterTabInactive: "text-link-muted hover:text-white",
  promptChip:
    "rounded-full border border-bdr px-4 py-2 text-small font-normal text-w-30 transition-colors hover:border-bdr-mid hover:text-w-60 disabled:cursor-not-allowed disabled:opacity-50",
} as const;

export const stateClasses = {
  projectCardTitleHover: "transition-colors group-hover:text-white",
  serviceCardBorderHover: "transition-colors hover:border-bdr-mid",
  nextProjectIconHover:
    "transition-[transform,color] group-hover:text-w-60 group-active:text-accent",
} as const;
